services:
  - type: web
    name: meteora-token-launcher
    runtime: node
    plan: starter  # ~$7/month
    repo: https://github.com/ledgone09/meteora.git
    branch: main
    rootDir: .
    buildCommand: |
      echo "Starting build process..."
      npm install
      echo "Root dependencies installed"
      cd client
      echo "Building React frontend..."
      npm install
      npm run build
      echo "React build completed"
      ls -la build/
      cd ..
      echo "Build process complete"
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        generateValue: true
      - key: RPC_URL
        value: https://magical-boldest-patina.solana-mainnet.quiknode.pro/a94255dcbb27e52b1d4cca35d10e899b82b6bdba/
      - key: IPFS_GATEWAY
        value: https://ipfs.io/ipfs/
      - key: BASE_LAUNCH_PRICE
        value: "0.02"
      - key: PREMIUM_LAUNCH_PRICE  
        value: "0.1"
      - key: GENERATE_SOURCEMAP
        value: "false"
      - key: DISABLE_ESLINT_PLUGIN
        value: "true"
